"""Added name and surname

Revision ID: d7083d1648f1
Revises: 1ef6e827d54d
Create Date: 2019-10-30 18:54:56.674983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7083d1648f1'
down_revision = '058939c545ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=256, collation='ru-RU-x-icu'), nullable=True))
    op.add_column('users', sa.Column('surname', sa.String(length=256, collation='ru-RU-x-icu'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
